### ISSUE TITLE
Sample code not runnable

### ISSUE THREAD

**Issue by yilinshen** [usc-sail/peft-ser#2]
```
# whisper style loading
import torch
import peft_ser
model = peft_ser.load_model("whisper-base-lora-16-conv")

data = torch.zeros([1, 16000])
output = model(data)
logits = torch.softmax(output, dim=1)
```

It shows the following error "Whisper expects the mel input features to be of length 3000, but found 100. Make sure to pad the input mel features to 3000."

After changing `data = torch.zeros([1, 16000])` to `data = torch.zeros([1, 480000])` to match length 3000, it shows another error "{AssertionError}AssertionError('SER training was using 10s window frame, please crop your data to 10s')"

**Comment by tiantiaf0627** [comment]
Thanks for pointing this out, I think this was introduced from a recent transformer update in the whisper file: https://github.com/huggingface/transformers/blob/main/src/transformers/models/whisper/modeling_whisper.py#L1164

So I guess one fix would be trying with transformer version: 4.30.2, which is used in my environment, I tested it today and it works
<img width="552" alt="screenshot" src="https://github.com/usc-sail/peft-ser/assets/28857771/a5863270-ea5a-4016-b6c2-74fa094392e2">

**Comment by tiantiaf0627** [comment]
I also push an update to the published package, you may pip uninstall peft-ser and install it again to use it, let me know if you still face this issue

**Comment by yilinshen** [comment]
The code runs well now. Thank you
